Controllers/AddAppController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Server_Administration_Tool.Controllers
{
    [Authorize]
    public class AddAppController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddNewApplication()
        {
            return View();
        }

        public IActionResult AddExistingApplication()
        {
            return View();
        }
    }
}

Controllers/ApplicationsListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Server_Administration_Tool.Controllers
{
    [Authorize]
    public class ApplicationsListController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServerAdministrationTool.Models;
using System.Diagnostics;

namespace ServerAdministrationTool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }

        [Authorize]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ServerConfigController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Server_Administration_Tool.Controllers
{
	[Authorize]
	public class ServerConfigurationController : Controller
	{
		public IActionResult Index() 
		{
			return View();
		}
	}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная";
}

<div class="text-center">
    <img src="/src/server-minimalistic.png" style="width: 20%; margin-top: 5%;"></img>
    <p style="font-size: 1.5em;">Добро пожаловать в административную панель сервера</p>
    <br />
    <p>
        Выберите что бы вы хотели сделать
    </p>

    <div class="actions">
        <div class="container">
            <a asp-area="" asp-controller="AddApp">
                <img id="add-img" src="/src/add-button.png" />
                <p>Добавить приложение</p>
            </a>
            <a asp-area="" asp-controller="ApplicationsList">
                <img id="list-img" src="/src/document-text.png" />
                <p>Получить список размещенных приложений</p>
            </a>
            <a asp-area="" asp-controller="ServerConfiguration">
                <img id="gear-img" src="/src/settings.png" />
                <p>Получить сведения о системе</p>
            </a>
        </div>
    </div>
</div>